Accounting:
  children:
    db_servers:
      hosts:
        DB:
          ansible_host: 15.156.193.174
    lb_servers:
      hosts:
        LB:
          ansible_host: 3.97.8.60
    web_servers:
      hosts:
        WEB:
          ansible_host: 3.96.144.198
  vars:
    ansible_ssh_private_key_file: ../app-key.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    ansible_user: ubuntu
    app_name: Test
    db_port: 27017
    db_servers:
    - 192.168.0.13
    lb_port: 80
    web_server_port: 8080
    web_servers:
    - 192.168.0.12